import { FilterType, Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Blue Denim Jacket",
    price: 60,
    image: "https://image.hm.com/assets/hm/01/22/012296fb34bf6032135318932fc106e28236b54c.jpg?imwidth=2160",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["denim", "jacket", "blue"],
    condition: "Good",
    brand: "H&M"
  },
  {
    id: "2",
    title: "Yellow Cotton Tee",
    price: 20,
    image: "https://www.veromoda.in/cdn/shop/files/244532801_g5.jpg?v=1745700041&width=1080",
    category: FilterType.TOPS,
    size: "L",
    tags: ["tshirt", "Yellow", "casual"],
    condition: "New",
    brand: "Vero Moda"
  },
  {
    id: "3",
    title: "Blue Sweatpants",
    price: 32,
    image: "https://assets.aritzia.com/image/upload/c_crop,ar_1920:2623,g_south/q_auto,f_auto,dpr_auto/f25_a06_116230_30397_on_b",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["sweatpants", "blue", "casual"],
    condition: "Good",
    brand: "Aritzia"
  },
  {
    id: "4",
    title: "Leather Jacket Black",
    price: 120,
    image: "https://www.voganow.com/cdn/shop/files/VNGJ-113-LU-12_1_copy.jpg?v=1752277932",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["leather", "jacket", "black"],
    condition: "Like New",
    brand: "Voga"
  },
  {
    id: "5",
    title: "Green Windbreaker Jacket",
    price: 55,
    image: "https://cdn-images.farfetch-contents.com/27/56/66/59/27566659_57347666_600.jpg",
    category: FilterType.OUTERWEAR,
    size: "L",
    tags: ["windbreaker", "green", "casual"],
    condition: "Good",
    brand: "Farfetch"
  },
  {
    id: "6",
    title: "Khaki Cargo Pants",
    price: 40,
    image: "https://www.ruff.in/cdn/shop/files/12320_RE_KHAKHI_1_a82ed325-003b-4021-b8be-ee114e716e07.jpg?v=1739353409&width=1090",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["cargo", "khaki", "streetwear"],
    condition: "Good",
    brand: "Ruff"
  },
  {
    id: "7",
    title: "Dark Slim Jeans",
    price: 45,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbJ--2jfr1LPwBmvvlYGwbppsFqfXYXCnFug&s",
    category: FilterType.BOTTOMS,
    size: "32",
    tags: ["jeans", "denim", "blue"],
    condition: "Used",
    brand: "Unknown"
  },
  {
    id: "8",
    title: "Basic Long‑Sleeve Tee Black",
    price: 22,
    image: "https://www.universalstandard.com/cdn/shop/products/1069_LongSleeveTeeRex_Black_0140.jpg?v=1762274438&width=2000",
    category: FilterType.TOPS,
    size: "M",
    tags: ["long-sleeve", "black", "cotton"],
    condition: "New",
    brand: "Universal Standard"
  },
  {
    id: "9",
    title: "Beige Chino Shorts",
    price: 30,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkoZ3XKLeXfjDfSGJn5MeXScUCzaLS6VXjaQ&s",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["shorts", "beige", "summer"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "10",
    title: "Light‑Blue Denim Vest",
    price: 48,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4E4i6PphAPej57JJNTD_KriqYQLWtquFqTQ&s",
    category: FilterType.OUTERWEAR,
    size: "S",
    tags: ["denim", "vest", "light-blue"],
    condition: "Used",
    brand: "Unknown"
  },
  {
    id: "11",
    title: "Casual Hoodie – Charcoal",
    price: 38,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ15A3kGDxhWaw17CcJPiNOXw0kz2cQ6oVyA&s",
    category: FilterType.TOPS,
    size: "L",
    tags: ["hoodie", "charcoal", "casual"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "12",
    title: "Black Joggers",
    price: 34,
    image: "https://www.iconicindia.com/cdn/shop/files/2402-MMFP00402-FA150168-9000_5.jpg?v=1754662214&width=1445",
    category: FilterType.BOTTOMS,
    size: "L",
    tags: ["joggers", "black", "sport"],
    condition: "New",
    brand: "Iconic India"
  },
  {
    id: "13",
    title: "Pink Jacket",
    price: 70,
    image: "https://cpimg.tistatic.com/07209230/b/4/Ladies-Jacket.jpg",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["girls", "jacket", "pink"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "14",
    title: "Red Tank Top",
    price: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQri8pqabHxlU0e0NDrKQpvFAWEKILFddgq2w&s",
    category: FilterType.TOPS,
    size: "S",
    tags: ["tank-top", "Red", "summer"],
    condition: "New",
    brand: "Unknown"
  },
  {
    id: "15",
    title: "Grey Sweatshirt",
    price: 35,
    image: "https://assets.myntassets.com/w_412,q_30,dpr_3,fl_progressive,f_webp/assets/images/2025/OCTOBER/25/1iVtOcD6_740c055cc91848df8e2a66593a5aca51.jpg",
    category: FilterType.TOPS,
    size: "XL",
    tags: ["sweatshirt", "grey", "cozy"],
    condition: "Good",
    brand: "Myntra"
  },
  {
    id: "16",
    title: "Blue Denim Jacket",
    price: 60,
    image: "https://image.hm.com/assets/hm/01/22/012296fb34bf6032135318932fc106e28236b54c.jpg?imwidth=2160",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["denim", "jacket", "blue"],
    condition: "Good",
    brand: "H&M"
  },
  {
    id: "17",
    title: "Yellow Cotton Tee",
    price: 20,
    image: "https://www.veromoda.in/cdn/shop/files/244532801_g5.jpg?v=1745700041&width=1080",
    category: FilterType.TOPS,
    size: "L",
    tags: ["tshirt", "Yellow", "casual"],
    condition: "New",
    brand: "Vero Moda"
  },
  {
    id: "18",
    title: "Blue Sweatpants",
    price: 32,
    image: "https://assets.aritzia.com/image/upload/c_crop,ar_1920:2623,g_south/q_auto,f_auto,dpr_auto/f25_a06_116230_30397_on_b",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["sweatpants", "blue", "casual"],
    condition: "Good",
    brand: "Aritzia"
  },
  {
    id: "19",
    title: "Leather Jacket Black",
    price: 120,
    image: "https://www.voganow.com/cdn/shop/files/VNGJ-113-LU-12_1_copy.jpg?v=1752277932",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["leather", "jacket", "black"],
    condition: "Like New",
    brand: "Voga"
  },
  {
    id: "20",
    title: "Green Windbreaker Jacket",
    price: 55,
    image: "https://cdn-images.farfetch-contents.com/27/56/66/59/27566659_57347666_600.jpg",
    category: FilterType.OUTERWEAR,
    size: "L",
    tags: ["windbreaker", "green", "casual"],
    condition: "Good",
    brand: "Farfetch"
  },
  {
    id: "21",
    title: "Khaki Cargo Pants",
    price: 40,
    image: "https://www.ruff.in/cdn/shop/files/12320_RE_KHAKHI_1_a82ed325-003b-4021-b8be-ee114e716e07.jpg?v=1739353409&width=1090",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["cargo", "khaki", "streetwear"],
    condition: "Good",
    brand: "Ruff"
  },
  {
    id: "22",
    title: "Dark Slim Jeans",
    price: 45,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbJ--2jfr1LPwBmvvlYGwbppsFqfXYXCnFug&s",
    category: FilterType.BOTTOMS,
    size: "32",
    tags: ["jeans", "denim", "blue"],
    condition: "Used",
    brand: "Unknown"
  },
  {
    id: "23",
    title: "Basic Long‑Sleeve Tee Black",
    price: 22,
    image: "https://www.universalstandard.com/cdn/shop/products/1069_LongSleeveTeeRex_Black_0140.jpg?v=1762274438&width=2000",
    category: FilterType.TOPS,
    size: "M",
    tags: ["long-sleeve", "black", "cotton"],
    condition: "New",
    brand: "Universal Standard"
  },
  {
    id: "24",
    title: "Beige Chino Shorts",
    price: 30,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkoZ3XKLeXfjDfSGJn5MeXScUCzaLS6VXjaQ&s",
    category: FilterType.BOTTOMS,
    size: "M",
    tags: ["shorts", "beige", "summer"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "25",
    title: "Light‑Blue Denim Vest",
    price: 48,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4E4i6PphAPej57JJNTD_KriqYQLWtquFqTQ&s",
    category: FilterType.OUTERWEAR,
    size: "S",
    tags: ["denim", "vest", "light-blue"],
    condition: "Used",
    brand: "Unknown"
  },
  {
    id: "26",
    title: "Casual Hoodie – Charcoal",
    price: 38,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ15A3kGDxhWaw17CcJPiNOXw0kz2cQ6oVyA&s",
    category: FilterType.TOPS,
    size: "L",
    tags: ["hoodie", "charcoal", "casual"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "27",
    title: "Black Joggers",
    price: 34,
    image: "https://www.iconicindia.com/cdn/shop/files/2402-MMFP00402-FA150168-9000_5.jpg?v=1754662214&width=1445",
    category: FilterType.BOTTOMS,
    size: "L",
    tags: ["joggers", "black", "sport"],
    condition: "New",
    brand: "Iconic India"
  },
  {
    id: "28",
    title: "Pink Jacket",
    price: 70,
    image: "https://cpimg.tistatic.com/07209230/b/4/Ladies-Jacket.jpg",
    category: FilterType.OUTERWEAR,
    size: "M",
    tags: ["pink", "jacket", "girls"],
    condition: "Good",
    brand: "Unknown"
  },
  {
    id: "29",
    title: "Red Tank Top",
    price: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQri8pqabHxlU0e0NDrKQpvFAWEKILFddgq2w&s",
    category: FilterType.TOPS,
    size: "S",
    tags: ["tank-top", "Red", "summer"],
    condition: "New",
    brand: "Unknown"
  },
  {
    id: "30",
    title: "Grey Sweatshirt",
    price: 35,
    image: "https://assets.myntassets.com/w_412,q_30,dpr_3,fl_progressive,f_webp/assets/images/2025/OCTOBER/25/1iVtOcD6_740c055cc91848df8e2a66593a5aca51.jpg",
    category: FilterType.TOPS,
    size: "XL",
    tags: ["sweatshirt", "grey", "cozy"],
    condition: "Good",
    brand: "Myntra"
  },

];
